from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def load_findings(
    findings_dir: Path,
) -> list[dict[str, Any]]:

    findings: list[dict[str, Any]] = []

    if not findings_dir.exists():
        return findings

    for file in sorted(
        findings_dir.glob("*.json")
    ):
        data = json.loads(
            file.read_text(
                encoding="utf-8"
            )
        )

        findings.extend(
            data.get(
                "findings",
                []
            )
        )

    return findings


def classify_findings(
    findings: list[dict[str, Any]],
) -> tuple[
    list[dict[str, Any]],
    list[dict[str, Any]],
]:

    blocking = []
    advisory = []

    for finding in findings:

        status = finding.get(
            "verification_status",
            "UNVERIFIED",
        )

        severity = finding.get(
            "severity",
            "",
        ).upper()

        if status == "REFUTED":
            continue

        if (
            status == "VERIFIED"
            and severity
            in {"CRITICAL", "HIGH"}
        ):
            blocking.append(finding)

        else:
            advisory.append(finding)

    return blocking, advisory


def render_finding(
    finding: dict[str, Any],
) -> str:

    return f"""
### {finding.get("id", "UNKNOWN")} — {finding.get("title", "")}

- **Severity:** `{finding.get("severity", "UNKNOWN")}`
- **Category:** `{finding.get("category", "UNKNOWN")}`
- **Verification:** `{finding.get("verification_status", "UNVERIFIED")}`
- **File:** `{finding.get("file", "")}:{finding.get("line", "")}`

**Evidence**

{finding.get("evidence", "")}

**Impact**

{finding.get("impact", "")}

**Recommendation**

{finding.get("recommendation", "")}
""".strip()


def build_report_markdown(
    context: dict[str, Any],
    review_plan: dict[str, Any],
    findings: list[dict[str, Any]],
) -> str:

    blocking, advisory = (
        classify_findings(findings)
    )

    selected_reviewers = (
        review_plan.get(
            "selected_reviewers",
            [],
        )
    )

    risk_triggers = (
        review_plan.get(
            "risk_triggers",
            [],
        )
    )

    lines = [
        f"# PR Guardian Review — PR #{context.get('pr_id')}",
        "",
        f"**Repository:** `{context.get('repository_name', '')}`",
        "",
        f"**Title:** {context.get('title', '')}",
        "",
        f"**Risk Level:** `{review_plan.get('risk_level', 'UNKNOWN')}`",
        "",
        "## Summary",
        "",
        f"- Changed files: {context.get('changed_files_count', 0)}",
        f"- Additions: {context.get('additions', 0)}",
        f"- Deletions: {context.get('deletions', 0)}",
        f"- Findings: {len(findings)}",
        f"- Blocking: {len(blocking)}",
        f"- Advisory: {len(advisory)}",
        "",
        "## Reviewers",
        "",
    ]

    if selected_reviewers:
        for reviewer in selected_reviewers:
            lines.append(
                f"- `{reviewer}`"
            )
    else:
        lines.append(
            "No specialist reviewers selected."
        )

    lines.extend([
        "",
        "## Risk Triggers",
        "",
    ])

    if risk_triggers:
        for trigger in risk_triggers:
            lines.append(
                f"- `{trigger}`"
            )
    else:
        lines.append(
            "No specific risk triggers detected."
        )

    lines.extend([
        "",
        "## Blocking Findings",
        "",
    ])

    if blocking:
        for finding in blocking:
            lines.append(
                render_finding(finding)
            )
            lines.append("")
    else:
        lines.append(
            "No verified blocking findings."
        )

    lines.extend([
        "",
        "## Advisory Findings",
        "",
    ])

    if advisory:
        for finding in advisory:
            lines.append(
                render_finding(finding)
            )
            lines.append("")
    else:
        lines.append(
            "No advisory findings."
        )

    lines.extend([
        "",
        "## Review Result",
        "",
    ])

    if blocking:
        lines.append(
            "The review contains verified blocking findings."
        )
    elif advisory:
        lines.append(
            "The review contains advisory findings but no verified blocking findings."
        )
    else:
        lines.append(
            "No concrete findings were identified."
        )

    lines.extend([
        "",
        "---",
        "",
        "Generated by PR Guardian.",
    ])

    return "\n".join(lines)

def write_report(
    reports_root: Path,
    pr_id: str,
    context: dict[str, Any],
    review_plan: dict[str, Any],
) -> None:

    findings_dir = (
        reports_root
        / "findings"
        / pr_id
    )

    findings = load_findings(
        findings_dir
    )

    blocking, advisory = (
        classify_findings(findings)
    )

    review_data = {
        "pr_id": context.get("pr_id"),
        "repository": context.get(
            "repository_name",
            "",
        ),
        "risk_level": review_plan.get(
            "risk_level",
        ),
        "selected_reviewers": (
            review_plan.get(
                "selected_reviewers",
                [],
            )
        ),
        "blocking": blocking,
        "advisory": advisory,
    }

    review_dir = (
        reports_root
        / "reviews"
        / pr_id
    )

    review_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    (
        review_dir
        / "review.json"
    ).write_text(
        json.dumps(
            review_data,
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    markdown = build_report_markdown(
        context=context,
        review_plan=review_plan,
        findings=findings,
    )

    (
        review_dir
        / "review.md"
    ).write_text(
        markdown,
        encoding="utf-8",
    )